config/routes.rb
Rails.application.routes.draw do

  get  'cashorder/index'
  get  'chat/index'
  get  'errors/error404'
  get  'errors/error422'
  get  'errors/error500'
  get  'home/index'
  get  'user_sessions/new'
  get  'user_sessions/create'
  get  'user_sessions/destroy'
  get  'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

  resources :chat
  resources :agencies
  resources :microposts
  resources :orders, only: [:index]
  resources :tourists do
    resources :orders
  end
  # resources :orders, only: [:index]
  resources :user_sessions
  resources :users

  root :to => 'home#index'
end

app/models/tourist.rb
class Tourist < ActiveRecord::Base
  extend FriendlyId
  friendly_id :lastname_en
  has_many :orders
  accepts_nested_attributes_for :orders

  default_scope -> { order(:lastname_ua => :asc) }

  validates_presence_of :email
  validates :email,
    :presence => true,
    :format => { :with => /\A[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]+\z/ ,
      :message => 'Invalid e-mail! Please provide a valid e-mail address'},
      :on => :create

  def to_label
    "#{lastname_en}"
  end

  def to_name
    "#{lastname_en}"
  end

  def to_s
    "#{lastname_en}"
  end

  def self.search search
    where("id || email || phone_mobile || lastname_en || lastname_ua || add_lastname_en_one || add_lastname_en_two || add_lastname_en_three || add_lastname_en_four || add_lastname_en_five LIKE ?", "%#{search}%")
  end

  def tags_for_form
    collection = orders.where(tourist_id: id)
    collection.any? ? collection : orders.build
  end

end

app/controllers/tourists_controller.rb
class TouristsController < ApplicationController
  before_action :set_tourist, only: [:show, :edit, :update, :destroy]
  before_filter :load_tourist

  def index
    @tourists = Tourist.all
    @tourists = Tourist.search(params[:search])
    if @tourists.class == Array
      @tourists = Kaminari.paginate_array(@tourists).page(params[:page]).per(3)
    else
      @tourists = @tourists.page(params[:page]).per(15)
    end
  end

  def show
  end

  def new
    @tourist = Tourist.new
  end

  def edit
    @tourist = Tourist.friendly.find(params[:id])
  end

  def create
    @tourist = Tourist.new(tourist_params)

    respond_to do |format|
      if @tourist.save
        format.html { redirect_to @tourist, notice: 'Tourist was successfully created.' }
        format.json { render action: 'show', status: :created, location: @tourist }
      else
        format.html { render action: 'new' }
        format.json { render json: @tourist.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @tourist = Tourist.friendly.find(params[:id])

    respond_to do |format|
      if @tourist.update_attributes(tourist_params)
        format.html { redirect_to @tourist, notice: 'Tourist was successfully updated.' }
        format.json { render :show, status: :ok, location: @tourist }
      else
        format.html { render action: 'edit' }
        format.json { render json: @tourist.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @tourist = Tourist.friendly.find(params[:id])
    @tourist.destroy

    respond_to do |format|
      format.html { redirect_to tourists_url, notice: 'Tourist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def load_tourist
      @tourist = Tourist.friendly.find(params[:tourist_id]) if params[:tourist_id].present?
    end

    def set_tourist
      @tourist = Tourist.friendly.find(params[:id])
    end

    def tourist_params
      params.require(:tourist).permit(:client,
                                      :lastname_ua,
                                      :firstname_ua,
                                      :middlename_ua,
                                      :lastname_en,
                                      :firstname_en,
                                      :day_born,
                                      :gender,
                                      :add_lastname_en_one,
                                      :add_firstname_en_one,
                                      :add_passport_one,
                                      :add_day_born_one,
                                      :add_phone_one,
                                      :add_passport_day_issue_one,
                                      :add_passport_validity_one,
                                      :add_lastname_en_two,
                                      :add_firstname_en_two,
                                      :add_passport_two,
                                      :add_day_born_two,
                                      :add_phone_two,
                                      :add_passport_day_issue_two,
                                      :add_passport_validity_two,
                                      :add_lastname_en_three,
                                      :add_firstname_en_three,
                                      :add_passport_three,
                                      :add_day_born_three,
                                      :add_phone_three,
                                      :add_passport_day_issue_three,
                                      :add_passport_validity_three,
                                      :add_lastname_en_four,
                                      :add_firstname_en_four,
                                      :add_passport_four,
                                      :add_day_born_four,
                                      :add_phone_four,
                                      :add_passport_day_issue_four,
                                      :add_passport_validity_four,
                                      :add_lastname_en_five,
                                      :add_firstname_en_five,
                                      :add_passport_five,
                                      :add_day_born_five,
                                      :add_phone_five,
                                      :add_passport_day_issue_five,
                                      :add_passport_validity_five,
                                      :country,
                                      :foreign_suite,
                                      :foreign_number,
                                      :foreign_day_issue,
                                      :issued_by,
                                      :validity,
                                      :city,
                                      :street,
                                      :post_index,
                                      :house,
                                      :apartment,
                                      :phone_mobile,
                                      :phone_home,
                                      :phone_work,
                                      :email,
                                      :skype,
                                      :comment,
                                      :client_status,
                                      :learned_from,
                                      :msg_sms,
                                      :msg_mail,
                                      orders_attributes: [:id, :tourist_id, :_destroy ]
                                     )
    end
end

app/helpers/tourists_helper.rb
module TouristsHelper
end

app/views/tourists/_form.html.slim
= simple_form_for(@tourist) do |f|
  = f.error_notification

  .form-inputs
    = f.input :client, label: false, collection: [t('potential_customers'),t('current_customers')], include_blank: false, prompt: t('Client'), input_html: { style: 'width: 400px'}
    = f.input :lastname_ua, label: false, placeholder: t('Lastnameua'), input_html: { style: 'width: 400px'}
    = f.input :firstname_ua, label: false, placeholder: t('Firstnameua'), input_html: { style: 'width: 400px'}
    = f.input :middlename_ua, label: false, placeholder: t('Middlenameua'), input_html: { style: 'width: 400px'}
    = f.input :lastname_en, label: false, placeholder: t('Lastnameen'), input_html: { style: 'width: 400px'}
    = f.input :firstname_en, label: false, placeholder: t('Firstnameen'), input_html: { style: 'width: 400px'}
    = f.input :day_born, label: false, as: :special_picker, input_html: { :style=> 'width: 400px', class: 'datepicker'}, placeholder: t('Born')
    = f.input :gender, label: false, collection: [t('Male'), t('Female')], include_blank: false, prompt: t('Gender'), input_html: { style: 'width: 400px'}
    hr
      dd style="width:400px;"
        a href="#panel1"
          i class="fi-arrows-out size-16" style="float:right"
          '
          = t('accompanying')
        div id="panel1" class="content"
          h5 class="alert-base custom-bg " = t('accompany_one') 
          = f.input :add_lastname_en_one, label: false, placeholder: t('Lastnameen_one'), input_html: { style: 'width: 400px'}
          = f.input :add_firstname_en_one, label: false, placeholder: t('Firstnameen_one'), input_html: { style: 'width: 400px'}
          = f.input :add_passport_one, label: false, placeholder: t('Passport_one'), input_html: { style: 'width: 400px'}
          = f.input :add_day_born_one, label: false, placeholder: t('Day_born_one'), as: :special_picker, input_html: { style: 'width: 400px', class: 'datepicker'}
          = f.input :add_phone_one, label: false, placeholder: t('Phone_mobile_one'), input_html: { style: 'width: 400px'}
          = f.input :add_passport_day_issue_one, label: false, placeholder: t('Foreign day issue'), as: :special_picker, input_html: { style: 'width: 400px', class: 'datepicker'}
          = f.input :add_passport_validity_one, label: false, placeholder: t('Validity'), as: :special_picker, input_html: { style: 'width: 400px', class: 'datepicker'}
          = f.input :add_issued_by_one, label: false, placeholder: t('Issued by'), input_html: { style: 'width: 400px'}
          h5 class="alert-base custom-bg " = t('accompany_two')
          = f.input :add_lastname_en_two, label: false, placeholder: t('Lastnameen_two'), input_html: { style: 'width: 400px'}
          = f.input :add_firstname_en_two, label: false, placeholder: t('Firstnameen_two'), input_html: { style: 'width: 400px'}
          = f.input :add_passport_two, label: false, placeholder: t('Passport_three'), input_html: { style: 'width: 400px'}
          = f.input :add_day_born_two, label: false, placeholder: t('Day_born_two'), as: :special_picker, input_html: { :style=> 'width: 400px', class: 'datepicker'}
          = f.input :add_phone_two, label: false, placeholder: t('Phone_mobile_two'), input_html: { style: 'width: 400px'}
          = f.input :add_passport_day_issue_two, label: false, placeholder: t('Foreign day issue'), as: :special_picker, input_html: { style: 'width: 400px', class: 'datepicker'}
          = f.input :add_passport_validity_two, label: false, placeholder: t('Validity'), as: :special_picker, input_html: { style: 'width: 400px', class: 'datepicker'}
          = f.input :add_issued_by_two, label: false, placeholder: t('Issued by'), input_html: { style: 'width: 400px'}
          h5 class="alert-base custom-bg " = t('accompany_three')
          = f.input :add_lastname_en_three, label: false, placeholder: t('Lastnameen_three'), input_html: { style: 'width: 400px'}
          = f.input :add_firstname_en_three, label: false, placeholder: t('Firstnameen_three'), input_html: { style: 'width: 400px'}
          = f.input :add_passport_three, label: false, placeholder: t('Passport_three'), input_html: { style: 'width: 400px'}
          = f.input :add_day_born_three, label: false, placeholder: t('Day_born_three'), as: :special_picker, input_html: { :style=> 'width: 400px', class: 'datepicker'}
          = f.input :add_phone_three, label: false, placeholder: t('Phone_mobile_three'), input_html: { style: 'width: 400px'}
          = f.input :add_passport_day_issue_three, label: false, placeholder: t('Foreign day issue'), as: :special_picker, input_html: { style: 'width: 400px', class: 'datepicker'}
          = f.input :add_passport_validity_three, label: false, placeholder: t('Validity'), as: :special_picker, input_html: { style: 'width: 400px', class: 'datepicker'}
          = f.input :add_issued_by_three, label: false, placeholder: t('Issued by'), input_html: { style: 'width: 400px'}
          h5 class="alert-base custom-bg " = t('accompany_four')
          = f.input :add_lastname_en_four, label: false, placeholder: t('Lastnameen_four'), input_html: { style: 'width: 400px'}
          = f.input :add_firstname_en_four, label: false, placeholder: t('Firstnameen_four'), input_html: { style: 'width: 400px'}
          = f.input :add_passport_four, label: false, placeholder: t('Passport_four'), input_html: { style: 'width: 400px'}
          = f.input :add_day_born_four, label: false, placeholder: t('Day_born_four'), as: :special_picker, input_html: { :style=> 'width: 400px', class: 'datepicker'}
          = f.input :add_phone_four, label: false, placeholder: t('Phone_mobile_four'), input_html: { style: 'width: 400px'}
          = f.input :add_passport_day_issue_four, label: false, placeholder: t('Foreign day issue'), as: :special_picker, input_html: { style: 'width: 400px', class: 'datepicker'}
          = f.input :add_passport_validity_four, label: false, placeholder: t('Validity'), as: :special_picker, input_html: { style: 'width: 400px', class: 'datepicker'}
          = f.input :add_issued_by_four, label: false, placeholder: t('Issued by'), input_html: { style: 'width: 400px'}
          h5 class="alert-base custom-bg " = t('accompany_five')
          = f.input :add_lastname_en_five, label: false, placeholder: t('Lastnameen_five'), input_html: { style: 'width: 400px'}
          = f.input :add_firstname_en_five, label: false, placeholder: t('Firstnameen_five'), input_html: { style: 'width: 400px'}
          = f.input :add_passport_five, label: false, placeholder: t('Passport_five'), input_html: { style: 'width: 400px'}
          = f.input :add_day_born_five, label: false, placeholder: t('Day_born_five'), as: :special_picker, input_html: { :style=> 'width: 400px', class: 'datepicker'}
          = f.input :add_phone_five, label: false, placeholder: t('Phone_mobile_five'), input_html: { style: 'width: 400px'}
          = f.input :add_passport_day_issue_five, label: false, placeholder: t('Foreign day issue'), as: :special_picker, input_html: { style: 'width: 400px', class: 'datepicker'}
          = f.input :add_passport_validity_five, label: false, placeholder: t('Validity'), as: :special_picker, input_html: { style: 'width: 400px', class: 'datepicker'}
          = f.input :add_issued_by_five, label: false, placeholder: t('Issued by'), input_html: { style: 'width: 400px'}
    hr
    = f.input :country, label: false, priority: [ "Ukraine" ], prompt: t('select_country'), include_blank: false, input_html: { style: 'width: 400px'}
    = f.input :foreign_suite, label: false, placeholder: t('Foreign suite'), input_html: { style: 'width: 400px'}
    = f.input :foreign_number, label: false, placeholder: t('Foreign number'), input_html: { style: 'width: 400px'}
    = f.input :foreign_day_issue, label: false, placeholder: t('Foreign day issue'), as: :special_picker, input_html: { :style=> 'width: 400px', class: 'datepicker'}
    = f.input :issued_by, label: false, placeholder: t('Issued by'), input_html: { style: 'width: 400px'}
    = f.input :validity, label: false, placeholder: t('Validity'), as: :special_picker, input_html: { :style=> 'width: 400px', class: 'datepicker'}
    = f.input :city, label: false, placeholder: t('City'), input_html: { style: 'width: 400px'}
    = f.input :street, label: false, placeholder: t('Street'), input_html: { style: 'width: 400px'}
    = f.input :post_index, label: false, placeholder: t('Post index'), input_html: { style: 'width: 400px'}
    = f.input :house, label: false, placeholder: t('House'), input_html: { style: 'width: 400px'}
    = f.input :apartment, label: false, placeholder: t('Apartment'), input_html: { style: 'width: 400px'}
    = f.input :phone_mobile, label: false, placeholder: t('Phone_mobile'), input_html: {style: 'width: 400px'}
    = f.input :phone_home, label: false, placeholder: t('Phone_home'), input_html: { style: 'width: 400px'}
    = f.input :phone_work, label: false, placeholder: t('Phone_work'), input_html: { style: 'width: 400px'}
    = f.input :email, label: false, placeholder: t('Email'), input_html: { style: 'width: 400px'}
    = f.input :skype, label: false, placeholder: t('Skype'), input_html: { style: 'width: 400px'}
    = f.input :comment, label: false, placeholder: t('Comment'), as: :text, input_html: { style: 'width: 400px'}
    = f.input :client_status, label: false, collection: [t('new_customer'),t('regular_customer')], include_blank: false, prompt: t('Client status'), input_html: { style: 'width: 400px'}
    = f.input :learned_from, label: false, collection: [t('advice_of_friends'),t('internet'),t('google'),t('leaflets')], include_blank: false, prompt: t('Learned from'), input_html: { style: 'width: 400px'}
    h6 = t('Msg sms')
    '
    = f.input :msg_sms, label: false, as: :boolean, checked_value: 1, unchecked_value: 0
    h6 = t('Msg mail')
    '
    = f.input :msg_mail, label: false, as: :boolean, checked_value: 1, unchecked_value: 0


  .form-actions
    = f.button :submit, value: t('Save'), class: "btnbutton", style: "width:150px;max-width: 100%;height:42px;padding: 10px 10px 10px;"
    '
    = link_to t('Show'), @tourist, class: "btnBordered blueBtnBordered btnbutton", style: "width:150px;max-width:100%;height:42px;padding: 10px 10px 10px;"
    '
    = link_to t('Back'), tourists_path, class: "btnBordered blueBtnBordered btnbutton", style: "width:150px;max-width:100%;height:42px;padding: 10px 10px 10px;"

javascript:
  $('.datepicker').datepicker({
    format: "dd-mm-yyyy",
    todayHighlight: true,
    todayBtn: 'linked',
    autoclose: true,
    weekStart: 1,
    language: "uk"
  });

app/views/tourists/edit.html.slim
.row
  div class=["large-12", "columns"] style="top:30pt"
    div class="l-wrap--blog__post_tourist"
      a class="ad--tourist" href="/"
        strong class="ad__text_tourist size-24" = t('Editing tourist')

    == render 'form'

app/views/tourists/index.html.slim
.row
  div class=["large-12", "columns"] style="top:30pt"
    div class="l-wrap--blog__post_tourist"
      a class="ad--tourist" href="/"
        strong class="ad__text_tourist size-24" = t('Listing tourists')
    div class="row collapse"
      div class="small-2 large-1 columns"
        span class="prefix"
          i class="fi-page-search size-26"
      div class="small-10 large-11 columns"
        = form_tag(tourists_path, :method => "get", id: "search-form") do
          = search_field_tag :search, params[:search], placeholder: "#{t('search_tourist')}", class: 'auto_search'
          = submit_tag "Search", type: "hidden"

    table class="large-12"
      thead
        tr
          th width="40"  = t('customer_id')
          th class=["field_left"] width="130" = t('Lastnameua')
          th class=["field_left"] width="100" = t('Firstnameua')
          th class=["field_left"] width="130" = t('Lastnameen')
          th class=["field_left"] width="200" = t('Email')
          th width="110" = t('phone_mobile')
          th width="40"
          th width="40"
          th width="40"
      tbody
        - @tourists.each do |tourist|
          tr
            td class=["field_left"] = tourist.id
            td class=["field_left"]
              = tourist.lastname_ua
            td class=["field_left"] = tourist.firstname_ua
            td class=["field_left"] style="font-size:10pt;font-weight:600"
              = link_to tourist.lastname_en, {:controller => 'orders', :tourist_id => tourist.id}
            td class=["field_left"] = mail_to tourist.email, nil, style: 'font-weight: bold'
            td = tourist.phone_mobile
            td = link_to '<i class="effect1 fi-results-demographics size-32"></i>'.html_safe, tourist
            td = link_to '<i class="fi-pencil size-24"></i>'.html_safe, edit_tourist_path(tourist)
            td = link_to '<i class="fi-trash size-24"></i>'.html_safe, tourist, data: {:confirm => t('Are you sure?')}, :method => :delete
    table class="small-centered columns" cellspacing="0" cellpadding="0" style="border-collapse: collapse;border: 0px;"
      tbody
        td
          div class="flickr_pagination"
            = paginate @tourists
    table class="large-centered columns" cellspacing="0" cellpadding="0" style="border-collapse: collapse;border: 0px;width:805px"
      tbody
        td
          ul class="button-group round"
            li = link_to t('New User'), new_tourist_path, class: "btnBordered blueBtnBordered btnbutton", style: "width:235px;max-width: 100%;"
            li = link_to t('Order'),  orders_path, class: "btnBordered blueBtnBordered btnbutton", style: "width:165px;max-width: 100%;"
            li = link_to t('Agency_name'), agencies_path, class: "btnBordered blueBtnBordered btnbutton", style: "width:165px; max-width: 100%;"
            li = link_to t('Forum edit'), microposts_path, class: "btnBordered blueBtnBordered btnbutton", style: "width:235px;max-width: 100%;"

app/views/tourists/new.html.slim
.row
  div class=["large-12", "columns"] style="top:30pt"
    div class="l-wrap--blog__post_tourist"
      a class="ad--tourist" href="/"
        strong class="ad__text_tourist size-24" = t('New tourist')

    == render 'form'