config/routes.rb
Rails.application.routes.draw do

  get  'cashorder/index'
  get  'chat/index'
  get  'errors/error404'
  get  'errors/error422'
  get  'errors/error500'
  get  'home/index'
  get  'user_sessions/new'
  get  'user_sessions/create'
  get  'user_sessions/destroy'
  get  'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

  resources :chat
  resources :agencies
  resources :microposts
  resources :orders, only: [:index]
  resources :tourists do
    resources :orders
  end
  # resources :orders, only: [:index]
  resources :user_sessions
  resources :users

  root :to => 'home#index'
end

app/models/agency.rb
class Agency < ActiveRecord::Base
  extend FriendlyId
  friendly_id :agency_name
  has_many :orders, :dependent => :destroy

  def to_label
    "#{agency_name}"
  end

  def to_s
    "#{agency_name}"
  end

  def self.search search
    where("agency_name || agency_phone_work || agency_phone_work || agency_phone_mobile || agency_email_one || agency_email_two || agency_email_three LIKE ?", "%#{search}%")
  end
end

app/controllers/agencies_controller.rb
class AgenciesController < ApplicationController
  before_action :set_agency, only: [:show, :edit, :update, :destroy]

  def index
    @agencies = Agency.all
  end

  def show
  end

  def new
    @agency = Agency.new
  end

  def edit
  end

  def create
    @agency = Agency.new(agency_params)

    respond_to do |format|
      if @agency.save
        format.html { redirect_to @agency, notice: 'Agency was successfully created.' }
        format.json { render :show, status: :created, location: @agency }
      else
        format.html { render :new }
        format.json { render json: @agency.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @agency.update(agency_params)
        format.html { redirect_to @agency, notice: 'Agency was successfully updated.' }
        format.json { render :show, status: :ok, location: @agency }
      else
        format.html { render :edit }
        format.json { render json: @agency.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @agency.destroy
    respond_to do |format|
      format.html { redirect_to agencies_url, notice: 'Agency was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_agency
      @agency = Agency.friendly.find(params[:id])
    end

    def agency_params
      params.require(:agency).permit(
        :agency_name,
        :agency_pn,
        :agency_edrpoy,
        :agency_city,
        :agency_street,
        :agency_post_index,
        :agency_house,
        :agency_apart,
        :city_legal,
        :street_legal,
        :post_index_legal,
        :house_legal,
        :apart_legal,
        :agency_phone_work,
        :agency_phone_mobile,
        :agency_email_one,
        :agency_email_two,
        :agency_email_three,
        :agency_web,
        :agency_comment,
        :bank, :mfo,
        :account,
        :contract_number,
        :contract_from
      )
    end
end

app/helpers/agencies_helper.rb
module AgenciesHelper
end

app/views/agencies/_form.html.slim
= simple_form_for(@agency) do |f|
  = f.error_notification

  .form-inputs
    h5 class="alert-base custom-bg" style="width:400px;" = t('Touragency')
    = f.input :agency_name, label: false, placeholder: t('agency_name'), input_html: { style: 'width: 400px'}
    = f.input :agency_pn, label: false, placeholder: t('agency_pn'), input_html: { style: 'width: 400px'}
    = f.input :agency_edrpoy, label: false, placeholder: t('agency_edrpoy'), input_html: { style: 'width: 400px'}
    h5 class="alert-base custom-bg" style="width:400px;" = t('physical_address')
    = f.input :agency_city, label: false, placeholder: t('agency_city'), input_html: { style: 'width: 400px'}
    = f.input :agency_street, label: false, placeholder: t('agency_street'), input_html: { style: 'width: 400px'}
    = f.input :agency_post_index, label: false, placeholder: t('agency_post_index'), input_html: { style: 'width: 400px'}
    = f.input :agency_house, label: false, placeholder: t('agency_house'), input_html: { style: 'width: 400px'}
    = f.input :agency_apart, label: false, placeholder: t('agency_apart'), input_html: { style: 'width: 400px'}
    h5 class="alert-base custom-bg" style="width:400px;" = t('legal_address')
    = f.input :city_legal, label: false, placeholder: t('city_legal'), input_html: { style: 'width: 400px'}
    = f.input :street_legal, label: false, placeholder: t('street_legal'), input_html: { style: 'width: 400px'}
    = f.input :post_index_legal, label: false, placeholder: t('post_index_legal'), input_html: { style: 'width: 400px'}
    = f.input :house_legal, label: false, placeholder: t('house_legal'), input_html: { style: 'width: 400px'}
    = f.input :apart_legal, label: false, placeholder: t('apart_legal'), input_html: { style: 'width: 400px'}
    = f.input :agency_phone_work, label: false, placeholder: t('agency_phone_work'), input_html: { style: 'width: 400px'}
    = f.input :agency_phone_mobile, label: false, placeholder: t('agency_phone_mobile'), input_html: { style: 'width: 400px'}
    h5 class="alert-base custom-bg" style="width:400px;" = t('agency_contact')
    = f.input :agency_email_one, label: false, placeholder: t('agency_email_one'), input_html: { style: 'width: 400px'}
    = f.input :agency_email_two, label: false, placeholder: t('agency_email_two'), input_html: { style: 'width: 400px'}
    = f.input :agency_email_three, label: false, placeholder: t('agency_email_three'), input_html: { style: 'width: 400px'}
    = f.input :agency_web, label: false, placeholder: t('agency_web'), input_html: { style: 'width: 400px'}
    = f.input :agency_comment, label: false, placeholder: t('agency_comment'), input_html: { style: 'width: 400px'}
    h5 class="alert-base custom-bg" style="width:400px;"  = t('bank_account')
    = f.input :bank, label: false, placeholder: t('bank'), input_html: { style: 'width: 400px'}
    = f.input :mfo, label: false, placeholder: t('mfo'), input_html: { style: 'width: 400px'}
    = f.input :account, label: false, placeholder: t('current_account'), input_html: { style: 'width: 400px'}
    = f.input :contract_number, label: false, placeholder: t('contract_number'), input_html: { style: 'width: 400px'}
    = f.input :contract_from, label: false, placeholder: t('contract_from'), as: :special_picker, input_html: { style: 'width: 400px', class: 'datepicker'}

  .form-actions style="width:500px;"
    = f.button :submit, value: t('Save'), class: "btnbutton", style: "width:150px;max-width: 100%;height:42px;padding: 10px 10px 10px;"
    '
    = link_to t('Show'), @agency, class: "btnBordered blueBtnBordered btnbutton", style: "width:150px;max-width:100%;height:42px;padding: 10px 10px 10px;"
    '
    = link_to t('Back'), agencies_path, class: "btnBordered blueBtnBordered btnbutton", style: "width:150px;max-width:100%;height:42px;padding: 10px 10px 10px;"

javascript:
  $('.datepicker').datepicker({
    format: "dd-mm-yyyy",
    todayHighlight: true,
    todayBtn: 'linked',
    autoclose: true,
    weekStart: 1,
    language: "uk"
  });

app/views/agencies/edit.html.slim
.row
  div class=["small-centered", "columns"] style="top:30pt;width:900px"
    div class="l-wrap--blog__post_agency"
      a class="ad--agency" href="/"
        strong class="ad__text_agency size-24" = t('Editing agency')

    == render 'form'

app/views/agencies/index.html.slim
.row
  div class=["small-centered", "columns"] style="top:30pt;width:900px"
    div class="l-wrap--blog__post_agency"
      a class="ad--agency" href="/"
        strong class="ad__text_agency size-24" = t('Listing agencies')
    table class="large-12"
      thead
        tr
          th = t('agency_name')
          th width="115" = t('Phone work')
          th = t('Email one')
          th width="44"
          th width="44"
          th width="44"
      tbody
        - @agencies.each do |agency|
          tr
            td class=["field_left"] = agency.agency_name
            td = agency.agency_phone_work
            td class=["field_left"] = mail_to agency.agency_email_one, nil, style: 'font-weight: bold'
            td = link_to '<i class="fi-results-demographics size-32"></i>'.html_safe, agency
            td = link_to '<i class="fi-pencil size-24"></i>'.html_safe, edit_agency_path(agency)
            td = link_to '<i class="fi-trash size-24"></i>'.html_safe, agency, data: {:confirm => t('Are you sure?')}, :method => :delete
    table class="small-centered columns" cellspacing="0" cellpadding="0" style="border-collapse: collapse;border: 0px;width:870px"
      tbody
        td
          ul class="button-group round"
            li = link_to t('New Agency'), new_agency_path, class: "btnBordered blueBtnBordered btnbutton", style: "width:180px;max-width: 100%;"
            li = link_to t('Tourist'), tourists_path, class: "btnBordered blueBtnBordered btnbutton", style: "width:180px;max-width: 100%;"
            li = link_to t('Order'), orders_path, class: "btnBordered blueBtnBordered btnbutton", style: "width:180px; max-width: 100%;"
            li = link_to t('Forum edit'), microposts_path, class: "btnBordered blueBtnBordered btnbutton", style: "width:180px;max-width: 100%;"

app/views/agencies/new.html.slim
.row
  div class=["large-11", "columns"] style="top:30pt;"
    div class="l-wrap--blog__post_agency"
      a class="ad--agency" href="/"
        strong class="ad__text_agency size-24" = t('New agency')

    == render 'form'

app/views/agencies/show.html.slim
.row
  div class=["large-11", "columns"] style="top:30pt"
    div class="l-wrap--blog__post_agency"
      a class="ad--agency" href="/"
        strong class="ad__text_agency size-22" = t('Show agency')
    .row
      div class="large-12 columns"
        .row
          div class="small-12 columns"
            label = t('Agency name')
            div class="row display"
              div class="small-12 columns size-14"
                = @agency.agency_name
    .row
      div class="large-12 columns"
        .row
          div class="small-2 columns"
            label = t('Agency pn')
            div class="row display"
              div class="small-1 columns size-14"
                = @agency.agency_pn
          div class="small-2 columns"
            label = t('Agency edrpoy')
            div class="row display"
              div class="small-1 columns size-14"
                = @agency.agency_edrpoy
          div class="small-2 columns"
            label = t('Agency edrpoy')
            div class="row display"
              div class="small-1 columns size-14"
                = @agency.agency_edrpoy
    .row
      div class="large-12 columns"
        .row
          div class="small-2 columns"
            label = t('Agency city')
            div class="row display"
              div class="small-1 columns size-14"
                = @agency.agency_city
          div class="small-2 columns"
            label = t('Agency street')
            div class="row display"
              div class="small-1 columns size-14"
                = @agency.agency_street
          div class="small-2 columns"
            label = t('Agency post index')
            div class="row display"
              div class="small-1 columns size-14"
                = @agency.agency_post_index
          div class="small-2 columns"
            label = t('Agency house')
            div class="row display"
              div class="small-1 columns size-14"
                = @agency.agency_house
          div class="small-2 columns"
            label = t('Agency apart')
            div class="row display"
              div class="small-1 columns size-14"
                = @agency.agency_apart
    .row
      div class="large-12 columns"
        .row
          div class="small-2 columns"
            label = t('City legal')
            div class="row display"
              div class="small-1 columns size-14"
                = @agency.city_legal
          div class="small-2 columns"
            label = t('Street legal')
            div class="row display"
              div class="small-1 columns size-14"
                = @agency.street_legal
          div class="small-2 columns"
            label = t('Post index legal')
            div class="row display"
              div class="small-1 columns size-14"
                = @agency.post_index_legal
          div class="small-2 columns"
            label = t('House legal')
            div class="row display"
              div class="small-1 columns size-14"
                = @agency.house_legal
          div class="small-2 columns"
            label = t('Apart legal')
            div class="row display"
              div class="small-1 columns size-14"
                = @agency.apart_legal
    .row
      div class="large-12 columns"
        .row
          div class="small-2 columns"
            label = t('Agency phone work')
            div class="row display"
              div class="small-1 columns size-14"
                = @agency.agency_phone_work
          div class="small-2 columns"
            label = t('Agency phone mobile')
            div class="row display"
              div class="small-1 columns size-14"
                = @agency.agency_phone_mobile
          div class="small-2 columns"
            label = t('Agency email one')
            div class="row display"
              div class="small-1 columns size-14"
                = @agency.agency_email_one
          div class="small-2 columns"
            label = t('Agency email two')
            div class="row display"
              div class="small-1 columns size-14"
                = @agency.agency_email_two
          div class="small-2 columns"
            label = t('Agency email three')
            div class="row display"
              div class="small-1 columns size-14"
                = @agency.agency_email_three
          div class="small-2 columns"
            label = t('Agency web')
            div class="row display"
              div class="small-1 columns size-14"
                = @agency.agency_web
          div class="small-2 columns"
            label = t('Agency comment')
            div class="row display"
              div class="small-1 columns size-14"
                = @agency.agency_comment
    .row
      div class="large-12 columns"
        .row
          div class="small-2 columns"
            label = t('Bank')
            div class="row display"
              div class="small-6 columns size-14"
                = @agency.bank
          div class="small-2 columns"
            label = t('Mfo')
            div class="row display"
              div class="small-1 columns size-14"
                = @agency.mfo
          div class="small-2 columns"
            label = t('Account')
            div class="row display"
              div class="small-1 columns size-16"
                = @agency.account
          div class="small-2 columns"
            label = t('Contract number:')
            div class="row display"
              div class="small-1 columns size-14"
                = @agency.contract_number
          div class="small-2 columns"
            label = t('Contract from')
            div class="row display"
              - if @agency.contract_from.present?
                div class="small-1 columns size-14"
                  = @agency.contract_from.to_s(:month_and_year)
              - else
                div class="small-1 columns size-14"
                  = @agency.contract_from

    br
    = link_to t('Edit'), edit_agency_path(@agency), class: "btnBordered blueBtnBordered btnbutton"
    '
    = link_to t('Back'), agencies_path, class: "btnBordered blueBtnBordered btnbutton"