config/routes.rb
Rails.application.routes.draw do

  get  'cashorder/index'
  get  'chat/index'
  get  'errors/error404'
  get  'errors/error422'
  get  'errors/error500'
  get  'home/index'
  get  'user_sessions/new'
  get  'user_sessions/create'
  get  'user_sessions/destroy'
  get  'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

  resources :chat
  resources :agencies
  resources :microposts
  resources :orders, only: [:index]
  resources :tourists do
    resources :orders
  end
  # resources :orders, only: [:index]
  resources :user_sessions
  resources :users

  root :to => 'home#index'
end

app/models/order.rb
class Order < ActiveRecord::Base
  extend FriendlyId
  friendly_id :tourist_id
  belongs_to :agency
  belongs_to :tourist

  default_scope -> { joins(:tourist).order('tourists.lastname_en ASC, orders.tourist_id ASC') }

  validates :tourist_id, presence: true

  def to_label
    "#{tourist_id}"
  end

  def to_name
    "#{tourist_id}"
  end

  def to_s
    "#{tourist_id}"
  end

  def tourist_name
     tourist.name if tourist
  end

  def agency_name
    agency.name if agency
  end

  def self.search search
    where("id || tourist_id || tourists.lastname_en LIKE ?", "%#{search}%")
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :find_tourist

  def index
    @orders = @tourist.present? ? @tourist.orders : Order.all
    # @orders = Order.search(params[:search])

    if @orders.class == Array
      @orders = Kaminari.paginate_array(@orders).page(params[:page]).per(6)
    else
      @orders = @orders.page(params[:page]).per(15)
    end

    respond_to do |format|
      format.html
      format.json
    end
  end

  def show
    tourist = Tourist.friendly.find(params[:tourist_id])
    @order = tourist.orders.friendly.find(params[:id])

    respond_to do |format|
      format.html
      format.json  { render json: @order }
    end
  end

  def new
    tourist = Tourist.friendly.find(params[:tourist_id])
    @order = tourist.orders.build

    respond_to do |format|
      format.html
      format.json  { render json: @order }
    end
  end

  def edit
    tourist = Tourist.friendly.find(params[:tourist_id])
    @order = tourist.orders.friendly.find(params[:id])
  end

  def create
    tourist = Tourist.friendly.find(params[:tourist_id])
    @order = tourist.orders.create(order_params)
    @order.tourist = @tourist

    respond_to do |format|
      if @order.save
        format.html { redirect_to [@order.tourist, @order], notice: 'Order was successfully created.' }
        format.json { render action: 'show', status: :created, location: [@order.tourist, @order] }
      else
        format.html { render action: 'new' }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    tourist = Tourist.friendly.find(params[:tourist_id])
    @order = tourist.orders.friendly.find(params[:id])

    respond_to do |format|
      if @order.update_attributes(order_params)
        format.html { redirect_to [@order.tourist, @order], notice: 'Order was successfully updated.' }
        format.json { render action: 'show', status: :ok, location: [@order.tourist, @order] }
      else
        format.html { render action: 'edit' }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    tourist = Tourist.friendly.find(params[:tourist_id])
    @order = tourist.orders.friendly.find(params[:id])
    @order.destroy

    respond_to do |format|
      format.html { redirect_to tourist_orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def order_params
      params.require(:order).permit(
        :tourist_id,
        :odd,
        :mark,
        :order_day,
        :country,
        :tour_day_begin,
        :tour_day_end,
        :night,
        :aircross_begin,
        :aircross_end,
        :airtable,
        :airclass,
        :airline,
        :hotel_begin,
        :hotel_end,
        :hotel_name,
        :hotel_class,
        :hotel_city,
        :hotel_class_room,
        :hotel_pay,
        :service_begin,
        :service_end,
        :service_name,
        :medical_begin,
        :medical_end,
        :medical_name,
        :visa_begin,
        :visa_end,
        :visa_need,
        :agency_id,
        :payment_tour,
        :payment_currency,
        :sell_tour,
        :sell_currency,
        :operator,
        :operator_currency,
        :in_total,
        :total_currency,
        :paid,
        :paid_currency,
        :debt,
        :debt_currency,
        tourists_attributes: [ :id, :lastname_en, :_destroy ]
      )
    end

    def find_tourist
      if params[:tourist_id]
        @tourist = Tourist.friendly.find(params[:tourist_id])
      end
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.slim
= simple_form_for([@order.tourist, @order]) do |f|
  = f.error_notification

  .form-inputs
    = f.association :tourist, collection: Tourist.all, label: false, prompt: t('tourist_id'), input_html: { style: 'width: 400px'}
    = f.input :odd, label: false, placeholder: t('odd'), input_html: { style: 'width: 400px'}
    = f.input :mark, label: false, placeholder: t('mark'), input_html: { style: 'width: 400px'}
    = f.input :order_day, label: false, placeholder: t('order_day'), as: :special_picker, input_html: { style: 'width: 400px', class: 'datepicker'}
    = f.input :country, label: false, prompt: t('country_id'), input_html: { style: 'width: 400px'}
    = f.input :tour_day_begin, label: false, placeholder: t('tour_day_begin'), as: :special_picker, input_html: { style: 'width: 400px', class: 'datepicker'}
    = f.input :tour_day_end, label: false, placeholder: t('tour_day_end'), as: :special_picker, input_html: { style: 'width: 400px', class: 'datepicker'}
    = f.input :night, label: false, prompt: t('night'), collection: 1..31, input_html: { style: 'width: 400px'}
    = f.input :aircross_begin, label: false, placeholder: t('aircross_begin'), as: :special_picker, input_html: { style: 'width: 400px', class: 'datepicker'}
    = f.input :aircross_end, label: false, placeholder: t('aircross_end'), as: :special_picker, input_html: { style: 'width: 400px', class: 'datepicker'}
    = f.input :airtable, label: false, placeholder: t('airtable'), input_html: { style: 'width: 400px'}
    = f.input :airclass, label: false, prompt: t('airclass'), collection: [t('airclass econom'), t('airclass bussness')], input_html: { style: 'width: 400px'}
    = f.input :airline, label: false, placeholder: t('airline'), input_html: { style: 'width: 400px'}
    = f.input :hotel_begin, label: false, placeholder: t('hotel_begin'), as: :special_picker, input_html: { style: 'width: 400px', class: 'datepicker'}
    = f.input :hotel_end, label: false, placeholder: t('hotel_end'), as: :special_picker, input_html: { style: 'width: 400px', class: 'datepicker'}
    = f.input :hotel_name, label: false, placeholder: t('hotel_name'), input_html: { style: 'width: 400px'}
    = f.input :hotel_class, label: false, collection: 1..5, prompt: t('hotel_class'), input_html: { style: 'width: 400px'}
    = f.input :hotel_city, label: false, placeholder: t('hotel_city'), input_html: { style: 'width: 400px'}
    = f.input :hotel_pay, label: false, placeholder: t('hotel_room'), input_html: { style: 'width: 400px'}
    = f.input :hotel_class_room, label: false, prompt: t('hotel_class_food'), collection: ["BB","HB","FB","All","RO"], input_html: { style: 'width: 400px'}
    = f.input :service_begin, label: false, placeholder: t('service_begin'), as: :special_picker, input_html: { style: 'width: 400px', class: 'datepicker'}
    = f.input :service_end, label: false, placeholder: t('service_end'), as: :special_picker, input_html: { style: 'width: 400px', class: 'datepicker'}
    = f.input :service_name, label: false, prompt: t('service'), collection: [t('service_group'), t('service_personal')], input_html: { style: 'width: 400px'}
    = f.input :medical_begin, label: false, placeholder: t('medical_begin'), as: :special_picker, input_html: { style: 'width: 400px', class: 'datepicker'}
    = f.input :medical_end, label: false, placeholder: t('medical_end'), as: :special_picker, input_html: { style: 'width: 400px', class: 'datepicker'}
    = f.input :medical_name, label: false, placeholder: t('medecal_order'), input_html: { style: 'width: 400px'}
    = f.input :visa_begin, label: false, placeholder: t('visa_begin'), as: :special_picker, input_html: { style: 'width: 400px', class: 'datepicker'}
    = f.input :visa_end, label: false, placeholder: t('visa_end'), as: :special_picker, input_html: { style: 'width: 400px', class: 'datepicker'}
    = f.input :visa_need, label: false, prompt: t('visa'), collection: [t('visa_need'), t('visa_nonneed')], input_html: { style: 'width: 400px'}
    = f.association :agency, collection: Agency.all, label: false, prompt: t('agency_id'), input_html: { style: 'width: 400px'}
    = f.input :payment_tour, label: false, placeholder: t('payment_for'), input_html: { style: 'width: 400px'}
    = f.input :payment_currency, label: false, prompt: t('currency_value'), collection: [ "USD", "UAH", "EUR"], input_html: { style: 'width: 400px'}
    = f.input :sell_tour, label: false, placeholder: t('sell_tour'), input_html: { style: 'width: 400px'}
    = f.input :sell_currency, label: false, prompt: t('currency_value'), collection: [ "USD", "UAH", "EUR"], input_html: { style: 'width: 400px'}
    = f.input :operator, label: false, placeholder: t('operator'), input_html: { style: 'width: 400px'}
    = f.input :operator_currency, label: false, prompt: t('currency_value'), collection: [ "USD", "UAH", "EUR"], input_html: { style: 'width: 400px'}
    = f.input :in_total, label: false, placeholder: t('in_total'), input_html: { style: 'width: 400px'}
    = f.input :total_currency, label: false, prompt: t('currency_value'), collection: [ "USD", "UAH", "EUR"], input_html: { style: 'width: 400px'}
    = f.input :paid, label: false, placeholder: t('paid'), input_html: { style: 'width: 400px'}
    = f.input :paid_currency, label: false, prompt: t('currency_value'), collection: [ "USD", "UAH", "EUR"], input_html: { style: 'width: 400px'}
    = f.input :debt, label: false, placeholder: t('debt'), input_html: { style: 'width: 400px'}
    = f.input :debt_currency, label: false, prompt: t('currency_value'), collection: [ "USD", "UAH", "EUR"], input_html: { style: 'width: 400px'}

  .form-actions style="width:500px;"
    = f.button :submit, value: t('Save'), class: "btnbutton", style: "width:150px;max-width: 100%;height:42px;padding: 10px 10px 10px;"
    '
    = link_to t('Show'), [@order.tourist, @order], class: "btnBordered blueBtnBordered btnbutton", style: "width:150px;max-width:100%;height:42px;padding: 10px 10px 10px;"
    '
    = link_to t('Back'), tourist_orders_path(@order.tourist), class: "btnBordered blueBtnBordered btnbutton", style: "width:150px;max-width:100%;height:42px;padding:10px 10px 10px;"

javascript:
  $('.datepicker').datepicker({
    format: "dd-mm-yyyy",
    todayHighlight: true,
    todayBtn: 'linked',
    autoclose: true,
    weekStart: 1,
    language: "uk"
  });

app/views/orders/edit.html.slim
.row
  div class=["large-11", "columns"] style="top:30pt"
    div class="l-wrap--blog__post_order"
      a class="ad--order" href="/"
        strong class="ad__text_order size-24" = t('Editing order')

    == render 'form'

app/views/orders/index.html.slim
.row
  div class=["small-centered", "columns"] style="top:30pt;width:900px"
    div class="l-wrap--blog__post_order"
      a class="ad--order" href="/"
        strong class="ad__text_order size-24" = t('Listing orders')
    - if @tourist.present? && @tourist.orders && !@orders.blank?
    - else
      div class="row collapse"
        div class="small-2 large-1 columns"
          span class="prefix"
            i class="fi-page-search size-26"
        div class="small-10 large-11 columns"
          = form_tag(orders_path, :method => "get", id: "search-form") do
            = search_field_tag :search, params[:search], placeholder: "#{t('search_order')}", class: 'auto_search'
            = submit_tag "Search", type: "hidden"

    table class=["large-12"]
      thead
        tr
          th class=["field_left"] width="40"  = t('customer_id')
          th class=["field_left"] = t('Tourist')
          th class=["field_left"] width="160" = t('Country')
          th width="115" = t('Tour_day_begin')
          th width="115" = t('Tour_day_end')
          th width="115" = t('Payment_tour')
          th width="40"
          th width="40"
          th width="40"
      tbody
        - @orders.each do |order|
          tr
            td class=["field_left"] = order.tourist_id
            td class=["field_left"] = order.tourist
            td class=["field_left"] = t(order.country)
            td
              - if order.tour_day_begin.present?
                = order.tour_day_begin.to_s(:month_and_year)
              - else
                = order.tour_day_begin
            td
              - if order.tour_day_end.present?
                = order.tour_day_end.to_s(:month_and_year)
              - else
                = order.tour_day_end
            td = order.payment_tour
            td width="44" = link_to '<i class="fi-results-demographics size-32"></i>'.html_safe, [order.tourist, order]
            td width="44" = link_to '<i class="fi-pencil size-24"></i>'.html_safe, edit_tourist_order_path(order.tourist, order)
            td width="44" = link_to '<i class="fi-trash size-24"></i>'.html_safe, [order.tourist, order], data: {:confirm => t('Are you sure?')}, :method => :delete
    - if @orders.present?
      div class="small-centered large-10 columns"
        div(data-alert class="alert-box info radius")
          = t('Order done')
          = link_to '&times;'.html_safe, '#', :class => 'close'
    - else
        div class="small-centered large-11 columns"
          div(data-alert class="alert-box alert radius")
            = t('Non order')
    table class="small-centered columns" cellspacing="0" cellpadding="0" style="border-collapse: collapse;border: 0px;"
      tbody
        td
          div class="flickr_pagination"
            = paginate @orders
    table class="small-centered columns" cellspacing="0" cellpadding="0" style="border-collapse: collapse;border: 0px;width:880px"
      tbody
        td
          ul class="button-group round"
            - if @orders.present?
              li = link_to t('Tourist'), tourists_path, class: "btnBordered blueBtnBordered btnbutton", style: "width:150pt"
              li = link_to t('Agency_name'), agencies_path, class: "btnBordered blueBtnBordered btnbutton", style: "width:150pt"
              li = link_to t('Forum edit'), microposts_path, class: "btnBordered blueBtnBordered btnbutton", style: "width:155pt"
              li = link_to t('Main'), home_index_path, class: "btnBordered blueBtnBordered btnbutton", style: "width:155pt"
            - else
              li = link_to t('New Order'), new_tourist_order_path, class: "btnBordered blueBtnBordered btnbutton", style: "width:155pt"
              li = link_to t('Tourist'), tourists_path, class: "btnBordered blueBtnBordered btnbutton", style: "width:150pt"
              li = link_to t('Agency_name'), agencies_path, class: "btnBordered blueBtnBordered btnbutton", style: "width:150pt"
              li = link_to t('Forum edit'), microposts_path, class: "btnBordered blueBtnBordered btnbutton", style: "width:155pt"

app/views/orders/new.html.slim
.row
  div class=["large-11", "columns"] style="top:30pt"
    div class="l-wrap--blog__post_order"
      a class="ad--order" href="/"
        strong class="ad__text_order size-24" = t('New order')

    == render 'form'

app/views/orders/show.html.slim
.row
  div class=["large-11", "columns"] style="top:30pt"
    div class="l-wrap--blog__post_order"
      a class="ad--order" href="/"
        strong class="ad__text_order size-24" = t('Listing application')
    .row
      div class="large-9 columns"
        .row
          div class="small-5 columns"
            label = t('customer_name')
            div class="row display"
              div class="small-1 columns size-16"
                = @order.tourist
          div class="small-2 columns"
            label = t('Order id')
            div class="row display"
              div class="small-1 columns size-16"
                = @order.id
                '
                =@order.tourist_id
          div class="large-3 columns"
            label = t('odd')
            div class="row display"
              div class="small-1 columns size-16"
                = @order.odd
          div class="large-2 columns"
            label = t('mark')
            div class="row display"
              div class="small-1 columns size-16"
                = @order.mark
    .row
      div class="large-9 columns"
        .row
          div class="small-3 columns"
            label = t('Order day')
            div class="row display"
              - if @order.order_day.present?
                = @order.order_day.to_s(:month_and_year)
              - else
                = @order.order_day
          div class="small-2 columns"
            label = t('Country')
            div class="row display"
              = t(@order.country)
          div class="small-2 columns"
            label = t('Tour begin')
            div class="row display"
              - if @order.tour_day_begin.present?
                = @order.tour_day_begin.to_s(:month_and_year)
              - else
                = @order.tour_day_begin
          div class="small-2 columns"
            label = t('Tour end')
            div class="row display"
              - if @order.tour_day_end.present?
                = @order.tour_day_end.to_s(:month_and_year)
              - else
                = @order.tour_day_end
          div class="small-1 columns"
            label = t('Night')
            div class="row display"
              = @order.night
    .row
      div class="large-11 columns"
        .row
          div class="small-2 columns"
            label = t('Aircross begin')
            div class="row display"
              - if @order.aircross_begin.present?
                = @order.aircross_begin.to_s(:month_and_year)
              - else
                = @order.aircross_begin
          div class="small-2 columns"
            label = t('Aircross end')
            div class="row display"
              - if @order.aircross_end.present?
                = @order.aircross_end.to_s(:month_and_year)
              - else
                = @order.aircross_end
          div class="small-2 columns"
            label = t('Airtable')
            div class="row display"
              = @order.airtable
          div class="small-2 columns"
            label = t('Airclass')
            div class="row display"
              = @order.airclass
          div class="small-2 columns"
            label = t('Airline')
            div class="row display"
              = @order.airline
    .row
      div class="large-11 columns"
        .row
          div class="small-2 columns"
            label = t('Hotel begin')
            div class="row display"
              - if @order.hotel_begin.present?
                = @order.hotel_begin.to_s(:month_and_year)
              - else
                = @order.hotel_begin
          div class="small-2 columns"
            label = t('Hotel end')
            div class="row display"
              - if @order.hotel_end.present?
                = @order.hotel_end.to_s(:month_and_year)
              - else
                = @order.hotel_end
          div class="small-3 columns"
            label = t('Hotel name')
            div class="row display"
              = @order.hotel_name
          div class="small-2 columns"
            label = t('Hotel class')
            div class="row display"
              = @order.hotel_class
          div class="small-2 columns"
            label = t('Hotel city')
            div class="row display"
              = @order.hotel_city
    .row
      div class="large-11 columns"
        .row
          div class="small-2 columns"
            label = t('Hotel class room')
            div class="row display"
              = @order.hotel_class_room
          div class="small-2 columns"
            label = t('Hotel pay')
            div class="row display"
              = @order.hotel_pay
          div class="small-2 columns"
            label = t('Service begin')
            div class="row display"
              - if @order.service_begin.present?
                = @order.service_begin.to_s(:month_and_year)
              - else
                = @order.service_begin
          div class="small-2 columns"
            label = t('Service end')
            div class="row display"
              - if @order.service_end.present?
                = @order.service_end.to_s(:month_and_year)
              - else
                = @order.service_end
          div class="small-2 columns"
            label = t('Service name')
            div class="row display"
              = @order.service_name
    .row
      div class="large-11 columns"
        .row
          div class="small-2 columns"
            label = t('Medical begin')
            div class="row display"
              - if @order.medical_begin.present?
                = @order.medical_begin.to_s(:month_and_year)
              - else
                = @order.medical_begin
          div class="small-2 columns"
            label = t('Medical end')
            div class="row display"
              - if @order.medical_end.present?
                = @order.medical_end.to_s(:month_and_year)
              - else
                = @order.medical_end
          div class="small-8 columns"
            label = t('Medical name')
            div class="row display"
              = @order.medical_name
    .row
      div class="large-11 columns"
        .row
          div class="small-2 columns"
            label = t('Visa begin')
            div class="row display"
              - if @order.visa_begin.present?
                = @order.visa_begin.to_s(:month_and_year)
              - else
                = @order.visa_begin
          div class="small-2 columns"
            label = t('Visa end')
            div class="row display"
              - if @order.visa_end.present?
                = @order.visa_end.to_s(:month_and_year)
              - else
                = @order.visa_end
          div class="small-2 columns"
            label = t('Visa need')
            div class="row display"
              = @order.visa_need
          div class="small-5 columns"
            label = t('Agency')
            div class="row display"
              = @order.agency.to_s
    .row
      div class="large-11 columns"
        .row
          div class="small-2 columns"
            label = t('Payment tour')
            div class="row display"
              = @order.payment_tour
          div class="small-2 columns"
            label = t('Payment currency')
            div class="row display"
              = @order.payment_currency
          div class="small-2 columns"
            label = t('Sell tour')
            div class="row display"
              = @order.sell_tour
          div class="small-2 columns"
            label = t('Sell currency')
            div class="row display"
              = @order.sell_currency
    .row
      div class="large-11 columns"
        .row
          div class="small-2 columns"
            label = t('Operator')
            div class="row display"
              = @order.operator
          div class="small-2 columns"
            label = t('Operator currency')
            div class="row display"
              = @order.operator_currency
          div class="small-2 columns"
            label = t('In total')
            div class="row display"
              = @order.in_total
          div class="small-2 columns"
            label = t('Total currency')
            div class="row display"
              = @order.total_currency
    .row
      div class="large-11 columns"
        .row
          div class="small-2 columns"
            label = t('Paid')
            div class="row display"
              = @order.paid
          div class="small-2 columns"
            label = t('Paid currency')
            div class="row display"
              = @order.paid_currency
          div class="small-2 columns"
            label = t('Debt')
            div class="row display"
              = @order.debt
          div class="small-2 columns"
            label = t('Debt currency')
            div class="row display"
              = @order.debt_currency
    br
    = link_to t('Edit'), edit_tourist_order_path, class: "btnBordered blueBtnBordered btnbutton", style: "width:150px;max-width:100%;height:42px;padding:10px 10px 10px;"
    '
    = link_to t('Back'), tourist_orders_path(@order.tourist), class: "btnBordered blueBtnBordered btnbutton", style: "width:150px;max-width:100%;height:42px;padding:10px 10px 10px;"